### ISSUE TITLE
The plugin breaks vim's behavior regarding cursor column being maintained across lines

### ISSUE THREAD

**Issue by BlueInt32** [m4xshen/smartcolumn.nvim#10]
Hi! 
Vim has a silent way of maintaining the cursor column position across lines when we are moving from long to shorter lines and back to longer lines. 

The plugin breaks this behavior.

This issue is far easier to explain with videos though, so here it is with smarcolumn active: 

https://user-images.githubusercontent.com/2920038/224253120-82d78fb3-7a24-4718-965b-16bc54d1d2a0.mp4

--

And here is the normal default behavior, with smartcolumn disabled: 

https://user-images.githubusercontent.com/2920038/224253142-90775d66-8864-41c8-b44e-74bfeb1ef961.mp4

**Comment by TheFunctionalGuy** [comment]
Hey, I am already working on a solution. Expect a PR in a couple of minutes.

**Comment by m4xshen** [comment]
Fixed in 0c572e3eae48874f25b74394a486f38cadb5c958
