### ISSUE TITLE
Compatibility with virt-column.nvim

### ISSUE THREAD

**Issue by nkakouros** [m4xshen/smartcolumn.nvim#13]
When I use this plugin together with https://github.com/lukas-reineke/virt-column.nvim, the plugin generally works fine. There is only one issue. I have `scope = 'window'. When I open a file in which some lines are above 80 chars long, the displaying/hiding of the colorcolumn gets triggered only after I input a character. If I don't do that, the colorcolumn status does not get updated if I open/close folds, jump to lines, scroll, etc. Do you think it would be possible to investigate this?

**Comment by m4xshen** [comment]
You can add the following code to your config:
```lua
vim.api.nvim_create_autocmd({ "BufEnter", "CursorMoved", "CursorMovedI", "WinScrolled" }, {
   callback = function()
      vim.cmd("VirtColumnRefresh")
   end
})
```

**Comment by nkakouros** [comment]
Fantastic, thank you for the support!
