### ISSUE TITLE
Colorcolumn does not color subsequent "columns" when `wrap` is true

### ISSUE THREAD

**Issue by benjaminchristie** [m4xshen/smartcolumn.nvim#17]
For windows where `wrap` is true, the colorcolumn is not properly highlighted for subsequent "columns" on the same line. Below is a screenshot:

![image](https://github.com/m4xshen/smartcolumn.nvim/assets/52015426/b199a3cc-4635-42b3-a915-66ccd959d6d1)

To fix this, one needs to set `colorcolumn` to multiples of of `colorcolumn + screen_width - gutter_width`.

**Comment by m4xshen** [comment]
I just found that this is the default behavior of Neovim, so I prefer to not change this.
