### ISSUE TITLE
Colorcolumn does not disable for tex files if not set in custom_colorcolumn

### ISSUE THREAD

**Issue by NathanGavenski** [m4xshen/smartcolumn.nvim#19]
Hi,

I may be doing something wrong, but I was trying to turn off the colorcolumn for my latex files. Although I set it inside the dictionary `disable_filetypes`, it still showed up.

The first configuration I tried was:
```lua
local config = {
    colorcolumn = "100",
    disable_filetypes = { "help", "text", "tex", "markdown" },
}
```
Which was not disabled. I've made sure that the ` vim.api.nvim_buf_get_option(0, "filetype")` was the same that I added in the dictionary.

The config that worked was:
```lua
local config = {
    colorcolumn = "100",
    disable_filetypes = { "help", "text", "markdown" },
    custom_colorcolumn = { tex = "0" }
}
```

(I also tried setting it to "none", but it expects a number, so I set it to 0.

**Comment by m4xshen** [comment]
It should be `disabled_filetypes`. You miss a `d`.

**Comment by NathanGavenski** [comment]
You are more than right, sorry for that.
