### ISSUE TITLE
Does not behave correctly in Neovim nightly

### ISSUE THREAD

**Issue by sjclayton** [m4xshen/smartcolumn.nvim#20]
Color column will appear when crossing the configured column number, but then if you modify/delete text so it's less than the configured number, the color column stays visible when it should disappear.

**Comment by ctrlplusb** [comment]
Confirming the same, and adding that once it has been triggered to appear in one buffer it appears in all subsequent buffers.

**Comment by VladimirBeliakov** [comment]
Looks like the problem is here
https://github.com/m4xshen/smartcolumn.nvim/blob/a52915d6d9abf9972e249ebcffcc651cf9b062dd/lua/smartcolumn.lua#L79
Changing that to 
```
vim.wo[win].colorcolumn = '0'
```
solves the problem.

**Comment by m4xshen** [comment]
@VladimirBeliakov Thanks, the latest version should work now!
