### ISSUE TITLE
Disable in floating windows

### ISSUE THREAD

**Issue by uZer** [m4xshen/smartcolumn.nvim#8]
Hi,

I'm trying to find a way to exclude some buffers by type or name.
Some colorschemes use a different guibg for floating windows (`hi NormalFloat`) which becomes problematic with the colorcolumn.

Is there an option for this?

An example of the results I have with Mason plugin:
![image](https://user-images.githubusercontent.com/547609/221054548-97c1dbf9-fad5-4108-8047-71936081ef98.png)

**Comment by peglah** [comment]
local config = {
   disabled_filetypes = { "lazy", "mason" },
}

**Comment by uZer** [comment]
Oh thanks! Works perfectly.

I wasn't expecting those window to have a defined filetype.
For anyone who struggle with other buffers : `:set ft` to read the filetype of your window.
