### ISSUE TITLE
smartcolumn could pick up the column dynamically from the `textwidth` option

### ISSUE THREAD

**Issue by andrewferrier** [m4xshen/smartcolumn.nvim#9]
Vim/NeoVim have a `textwidth` option which specifies the max width of a buffer, which is already used by other plugins, Vim itself, etc. It can be set buffer-local, and can be overriden with `after/ftplugin` files, `autocmds`, etc. It would be really nice if `smartcolumn` could pick that up automatically, and I didn't need to specify the width in its options or provide file-type specific widths; unfortunately this feels like it somewhat violates the DRY principle in my configuration.

Great idea for a plugin, thanks!

**Comment by m4xshen** [comment]
Why do you want it to pick up the `textwidth` option?

**Comment by andrewferrier** [comment]
OK, I checked and I had a fundamental misunderstanding here. As someone who doesn't use `colorcolumn` today, I thought that it was a boolean option, driven purely off the current value of `textwidth`. I realize now I'm wrong - `colorcolumn` can be set independently. I don't see why that is (why would you ever want to set it to anything other than textwidth - for me the only purpose is to highlight lines that are too long?), but that's a NeoVim question, not a `smartcolumn.nvim` question.

That said, I would still love to be able to dynamically set `colorcolumn` = `textwidth`, and it would be nice if `smartcolumn` could pick up the value of `textwidth` automatically rather than me having to duplicate that logic.

Hope that helps as an explanation?

**Comment by andrewferrier** [comment]
One fantastic and flexible way to do this would be to allow `custom_colorcolumn` to optionally be a callback function rather than a table, so that custom logic could be used to set the value. That opens to the door to what I suggested and potentially many other options too...

**Comment by m4xshen** [comment]
> One fantastic and flexible way to do this would be to allow `custom_colorcolumn` to optionally be a callback function rather than a table, so that custom logic could be used to set the value. That opens to the door to what I suggested and potentially many other options too...

This approach sounds great! I'll consider adding this feature.

**Comment by nkakouros** [comment]
That would also make it possible to use the `colorcolumn` setting, which smartcolumn seems to ignore currently.

**Comment by m4xshen** [comment]
The `custom_colorcolumn` now accepts function!
